<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: DejaVu Sans, sans-serif; font-size: 13px; color: #222; }
  .page { padding: 40px; }
  .header { display: flex; justify-content: space-between; margin-bottom: 32px; }
  .company-name { font-size: 22px; font-weight: bold; color: #2563EB; }
  .company-details { font-size: 11px; color: #666; margin-top: 4px; line-height: 1.6; }
  .receipt-meta { text-align: right; }
  .receipt-title { font-size: 28px; font-weight: bold; color: #111; letter-spacing: 2px; }
  .receipt-number { font-size: 13px; color: #555; margin-top: 6px; }

  table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
  thead th {
    background: #2563EB; color: #fff;
    padding: 10px 12px; font-size: 11px;
    text-transform: uppercase; text-align: left;
  }
  thead th:last-child { text-align: right; }
  tbody td { padding: 10px 12px; border-bottom: 1px solid #f0f0f0; font-size: 12px; }
  tbody td:last-child { text-align: right; }

  .totals { width: 260px; margin-left: auto; }
  .totals-row {
    display: flex; justify-content: space-between;
    padding: 6px 0; font-size: 12px; border-bottom: 1px solid #f0f0f0;
  }
  .totals-row.grand {
    padding-top: 10px; border-bottom: none; border-top: 2px solid #2563EB;
  }
  .totals-row.grand .label { font-size: 15px; font-weight: bold; }
  .totals-row.grand .value { font-size: 16px; font-weight: bold; color: #2563EB; }

  .qr-section { display: flex; align-items: center; margin: 24px 0; }
  .qr-box { margin-right: 14px; }
  .qr-label { font-size: 11px; font-weight: bold; color: #333; }
  .qr-desc { font-size: 10px; color: #888; margin-top: 2px; }

  .footer { border-top: 1px solid #f0f0f0; padding-top: 16px;
            font-size: 10px; color: #aaa; text-align: center; margin-top: 24px; }
</style>
</head>
<body>
<div class="page">

  <div class="header">
    <div>
      <div class="company-name">{{ $company?->name ?? 'AkɔntLite' }}</div>
      <div class="company-details">
        @if($company?->address) {{ $company->address }}<br> @endif
        @if($company?->email) {{ $company->email }} @endif
      </div>
    </div>
    <div class="receipt-meta">
      <div class="receipt-title">RECEIPT</div>
      <div class="receipt-number">
        {{ $receipt->receipt_number ?? 'RCP-' . $receipt->id }}
      </div>
      <div style="font-size:11px;color:#888;margin-top:4px">
        {{ \Carbon\Carbon::parse($receipt->receipt_date)->format('d M Y') }}
      </div>
    </div>
  </div>

  @if($receipt->vendor_name || $receipt->customer_name)
  <div style="margin-bottom:24px">
    @if($receipt->vendor_name)
    <div style="font-size:10px;color:#888;text-transform:uppercase;margin-bottom:4px">
      From
    </div>
    <div style="font-size:15px;font-weight:bold">{{ $receipt->vendor_name }}</div>
    @endif
    @if($receipt->customer_name)
    <div style="font-size:10px;color:#888;text-transform:uppercase;margin:10px 0 4px">
      Issued To
    </div>
    <div style="font-size:14px">{{ $receipt->customer_name }}</div>
    @endif
  </div>
  @endif

  @if($items->count() > 0)
  <table>
    <thead>
      <tr>
        <th style="width:55%">Description</th>
        <th style="text-align:center">Qty</th>
        <th style="text-align:right">Amount</th>
      </tr>
    </thead>
    <tbody>
      @foreach($items as $item)
      <tr>
        <td>{{ $item->description }}</td>
        <td style="text-align:center">{{ $item->quantity }}</td>
        <td>{{ $receipt->currency }} {{ number_format($item->total, 2) }}</td>
      </tr>
      @endforeach
    </tbody>
  </table>
  @endif

  <div class="totals">
    <div class="totals-row">
      <span class="label">Subtotal</span>
      <span>{{ $receipt->currency }} {{ number_format($receipt->subtotal, 2) }}</span>
    </div>
    @if($receipt->tax_amount > 0)
    <div class="totals-row">
      <span class="label">Tax / VAT</span>
      <span>{{ $receipt->currency }} {{ number_format($receipt->tax_amount, 2) }}</span>
    </div>
    @endif
    <div class="totals-row grand">
      <span class="label">Total</span>
      <span class="value">
        {{ $receipt->currency }} {{ number_format($receipt->total_amount, 2) }}
      </span>
    </div>
  </div>

  @include('pdf.partials.qr', ['qrCode' => $qrCode])

  @if($receipt->notes)
  <div style="background:#f8fafc;border-left:3px solid #2563EB;padding:12px;margin-top:16px">
    <div style="font-size:10px;color:#888;text-transform:uppercase;margin-bottom:4px">Notes</div>
    <div style="font-size:11px;color:#555">{{ $receipt->notes }}</div>
  </div>
  @endif

  <div class="footer">Generated by AkɔntLite</div>
</div>
</body>
</html>